"""Fetch fresh Douyin cookies using Playwright headless Chromium.

Usage:
    python3 douyin_cookies.py                  # prints cookie file path
    python3 douyin_cookies.py -o /tmp/dy.txt   # custom output path

Programmatic:
    from douyin_cookies import refresh_cookies
    cookie_str = refresh_cookies("/path/to/cookies.txt")
"""

import argparse
import logging
import time
from pathlib import Path

logger = logging.getLogger(__name__)

DEFAULT_COOKIE_PATH = Path("~/douyin_cookies.txt").expanduser()

# Must match TikTokDownloader's UA for ABogus signature compatibility
DOUYIN_USER_AGENT = (
    "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
    "AppleWebKit/537.36 (KHTML, like Gecko) "
    "Chrome/139.0.0.0 Safari/537.36"
)


def refresh_cookies(output_path: str | Path = DEFAULT_COOKIE_PATH) -> str:
    """Visit douyin.com with headless Chromium, export cookies.
    Returns cookie string (name=value; ...) for direct use in HTTP headers.
    Also writes Netscape cookies.txt to output_path.
    """
    from playwright.sync_api import sync_playwright

    output_path = Path(output_path)

    with sync_playwright() as p:
        browser = p.chromium.launch(headless=True)
        context = browser.new_context(
            user_agent=DOUYIN_USER_AGENT,
            viewport={"width": 1920, "height": 1080},
        )
        page = context.new_page()

        page.goto("https://www.douyin.com/", wait_until="domcontentloaded", timeout=30000)
        time.sleep(3)
        page.goto("https://www.douyin.com/discover", wait_until="domcontentloaded", timeout=30000)
        time.sleep(2)

        cookies = context.cookies()
        browser.close()

    if not cookies:
        raise RuntimeError("No cookies obtained from douyin.com")

    _write_netscape_cookies(cookies, output_path)
    cookie_str = "; ".join(f"{c['name']}={c['value']}" for c in cookies)
    # Also write cookie string for easy consumption
    output_path.with_suffix(".str").write_text(cookie_str)
    logger.info("Wrote %d cookies to %s", len(cookies), output_path)
    return cookie_str


def _write_netscape_cookies(cookies: list[dict], path: Path) -> None:
    """Write cookies in Netscape/Mozilla cookies.txt format."""
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = ["# Netscape HTTP Cookie File", "# Generated by douyin_cookies.py", ""]
    for c in cookies:
        domain = c.get("domain", "")
        flag = "TRUE" if domain.startswith(".") else "FALSE"
        secure = "TRUE" if c.get("secure", False) else "FALSE"
        expiry = int(c.get("expires", 0))
        if expiry < 0:
            expiry = 0
        lines.append(
            f"{domain}\t{flag}\t{c.get('path', '/')}\t{secure}\t{expiry}\t{c.get('name', '')}\t{c.get('value', '')}"
        )
    path.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    logging.basicConfig(level=logging.INFO, format="%(message)s")
    parser = argparse.ArgumentParser(description="Fetch Douyin cookies")
    parser.add_argument("-o", "--output", default=str(DEFAULT_COOKIE_PATH))
    args = parser.parse_args()
    p = refresh_cookies(args.output)
    print(f"Cookies saved to: {p}")
